### ISSUE TITLE
Location in mobile Safari

### ISSUE THREAD

**Issue by habi** [ntzm/osm-address-collector#31]
On an iPhone 12 mini with iOS 16.1 in mobile Safari I cannot get a location lock.
I’m using 1Blocker as an ad blocker, but also cannot get a location lock when reloading the page with 'Turn off content blocker’.

Is there a way I can help to debug this?

**Comment by ntzm** [comment]
Ensure that precise location services are enabled for the browser, I can't remember exactly how to do this but I can check as my girlfriend has an iPhone.

**Comment by habi** [comment]
Location access is allowed for all sites.
![image](https://user-images.githubusercontent.com/1651235/205045514-5241253d-eb7a-4730-a052-196cb756fa07.png)

**Comment by ntzm** [comment]
Do you get a popup saying any of the following when trying to get the location:

- GPS permission denied
- GPS position unavailable
- GPS position timeout

?

**Comment by habi** [comment]
> Do you get a popup [...]

No, not at all!

**Comment by ntzm** [comment]
Ok, thanks that's helpful :)

**Comment by ntzm** [comment]
Will take a look at this next week when I have some free time

**Comment by cpmsmith** [comment]
Checked the console on my own phone: looks like it's not considering `touchstart` to be a user gesture? If the `onClick` function was just using click events I suspect it might work.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/9437625/209427146-57470ab0-0138-4fdb-a8e8-c5869b8aeb91.png">

**Comment by ntzm** [comment]
Ah, thanks for doing the investigation @cpmsmith. Sorry for my slowness on this, will fix this later today

**Comment by ntzm** [comment]
Please check that it works properly now, thanks for reporting @habi and the investigation @cpmsmith

**Comment by habi** [comment]
All good now, thanks for fixing!
![image](https://user-images.githubusercontent.com/1651235/212284940-ca191ec6-fc2b-4577-9d30-192b47f88dba.png)
